### ISSUE TITLE
add `upsertMany(...)` helper function

### ISSUE THREAD

**Issue by aleksa-krolls** [OpenFn/language-mssql#9]
We have `insertMany(...)`, but would be nice to also add `upsertMany(...)` as we did in `language-postgres`. I ask because WCS will be using both adaptors, so it would be good to have consistent options for easier transfer of mappings.

**Comment by taylordowns2000** [comment]
@aleksa-krolls , this is now closed, but since spinning up an MSSQL instance takes so long we'll wait until there's an actual request from a client to test the new function and build a release for prod. So it's here, and can be tested or used on the master branch of `language-mssql` but won't be released and consumed by OpenFn.org until the client is happy with the output.
